function msd_mat = calc_equib_msd(coord_mat, equib_timepoint)
%%calc_msd parses the time, mean x, y, and z coordinates to calculate the
%%msd of the mean coordinates generated by parse_coord_summary.m.
%
%   inputs :
%      coord_mat : A matrix where each row is a time point printout of a
%       ChromoShake simulation. The columns are Time, mean x, mean y, and
%       mean z coordinate.
%
%      equib_timepoint : A scalar variable specifying the time to begin
%      calculating the mean squared displacement. Note, starts at 1 and
%      must be a positive integer.
%
%   outputs :
%       msd_mad : A matrix where each row is a tau. Columns are tau (s) and
%       mean squared displacement.

%% Parse tau info
base_tau = coord_mat(2,1);
num_timepoints = size(coord_mat, 1) - equib_timepoint;
%% pre-allocate msd_mat
msd_mat = zeros(num_timepoints - 1, 2);
%% Loop to calc msd per tau
for tau = 1:num_timepoints - 1
    start_coords = coord_mat(equib_timepoint:end-tau, 2:end);
    end_coords = coord_mat(equib_timepoint+tau:end, 2:end);
    diff_coords = start_coords - end_coords;
    displacements_squared = sum(diff_coords.^2, 2);
    msd_mat(tau,1) = base_tau * tau;
    msd_mat(tau,2) = mean(displacements_squared);
end