%%Generate the dir_cell and label_cell for loop size
dir_cell = {...
    fullfile(pwd,'6kb_coord_summs'), ...
    fullfile(pwd,'10kb_coord_summs'), ...
    fullfile(pwd,'15kb_coord_summs'), ...
    fullfile(pwd,'20kb_coord_summs'), ...
    fullfile(pwd,'23kb_coord_summs') ...
    };

label_cell = {...
    'size_6kb', ...
    'size_10kb', ...
    'size_15kb', ...
    'size_20kb', ...
    'size_23kb' ...
    };